# @import ./places-post.http
@route = places
@version = v1



### @name get_id_places
# @ref create_place
GET http://0.0.0.0:3000/api/{{version}}/{{route}}/{{create_place.id}} HTTP/1.1

###
# @name get_all_places
GET http://0.0.0.0:3000/api/{{version}}/{{route}}/?page=1&limit=100 HTTP/1.1

###
# @name get_all_places_filtered
# @ref create_place_1
GET http://0.0.0.0:3000/api/{{version}}/{{route}}/?category=LIBRARY HTTP/1.1

###
# @name get_all_places_filtered_pagination
# need to create multiple create_place  
GET http://0.0.0.0:3000/api/{{version}}/{{route}}/?category=STUDY_SPACE&page=1&limit=2 HTTP/1.1

###
# @name get_all_places_filtered_pagination_page_2
# need to create multiple create_place  
GET http://0.0.0.0:3000/api/{{version}}/{{route}}/?category=STUDY_SPACE&page=2&limit=2 HTTP/1.1





### @name get_id_places_fail
GET http://0.0.0.0:3000/api/{{version}}/{{route}}/21 HTTP/1.1